language: haskell
env:
- GHCVER=7.8.4
- GHCVER=7.10.2
- GHCVER=head
matrix:
  allow_failures:
  - env: GHCVER=head
before_install:
- |
  if [ $GHCVER = `ghc --numeric-version` ]; then
    travis/cabal-apt-install --enable-tests $MODE
    export CABAL=cabal
  else
    travis_retry sudo add-apt-repository -y ppa:hvr/ghc
    travis_retry sudo apt-get update
    travis_retry sudo apt-get install cabal-install-1.22 ghc-$GHCVER happy
    export CABAL=cabal-1.22
    export PATH=/opt/ghc/$GHCVER/bin:$PATH
  fi
- $CABAL update
- |
  $CABAL install happy alex
  export PATH=$HOME/.cabal/bin:$PATH
install:
- $CABAL install --dependencies-only --enable-tests
- $CABAL configure -flib-Werror --enable-tests $MODE
script:
- ghc --numeric-version
- $CABAL check
- $CABAL build
- $CABAL test --show-details=always
deploy:
  provider: hackage
  username: AlexanderThiemann
  skip_cleanup: true
  on:
    condition: $GHCVER = 7.10.2
    tags: true
  password:
    secure: OPZtu+menzxIb+ez+9SXvT6ijqCI9zuh7EtDXIkgDcnW0Kfnfckj+z2uxy6V/iyWUEiWj5z5OiPPZO9czvKy7ysB/QQJUYiwU3k6OrYhrfMED0wS+9WaOZ8lyezvqOJ9YQfvWvfmCcBc3BTyjb6798UWbi0KQcdd5InCslkToXA=
